dist: bionic
language: scala

services:
  - docker

scala:
  - 0.24.0-bin-20200408-4cc224b-NIGHTLY
  - 2.13.1
  - 2.12.11
env:
  - TRAVIS_JDK="adopt@~1.8.0-0"
  - TRAVIS_JDK="adopt@~1.11.0-0"
  - TRAVIS_JDK="graalvm@~20.0.0"
# for scala 2: test only 2.12 @ 1.8 and 2.13 @ graalvm
jobs:
  exclude:
    - scala: 2.13.1
      env: TRAVIS_JDK="adopt@~1.8.0-0"
    - scala: 2.13.1
      env: TRAVIS_JDK="adopt@~1.11.0-0"
    - scala: 2.12.11
      env: TRAVIS_JDK="adopt@~1.11.0-0"
    - scala: 2.12.11
      env: TRAVIS_JDK="graalvm@~20.0.0"

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install:
  # akka build on jdk > 8 require JDK 8 installation
  - |
    if [[ "$TRAVIS_JDK" != 'adopt@~1.8.0-0' ]]; then
      jabba install adopt@~1.8.0-0
    fi
  - jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.jabba/jdk

# script for the default 'test' stage:
# dotty ready modules:
#  + actor/compile (no test code)
#  + actor-typed/{compile, CompileJdk9/compile} (no test code)
#  + slf4j/test
#  + actor-testkit/test
#  + actor-testkit-typed/test
#  + actor-tests/test
#  + actor-typed-tests/test
script:
  - sbt -jvm-opts .jvmopts-travis -Dakka.build.scalaVersion=$TRAVIS_SCALA_VERSION ";akka-actor-typed-tests/test ;akka-slf4j/test ;akka-actor-tests/test"
